import {
  Activity,
  CalendarDays,
  Bell,
  ClipboardCheck,
  Calculator,
  CreditCard,
  Droplets,
  FileLock2,
  HardDrive,
  Info,
  LayoutDashboard,
  ListTodo,
  NotebookTabs,
  Receipt,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  TrendingUp,
  Truck,
  UserRound,
  Users,
  Wallet,
} from "lucide-react"

export const navigationByRole = {
  Admin: [
    { label: "Dashboard", path: "/admin", icon: LayoutDashboard },
    { label: "Approvals", path: "/admin/approvals", icon: ClipboardCheck },
    { label: "Notifications", path: "/admin/notifications", icon: Bell },
    { label: "Daily Reports", path: "/admin/daily-reports", icon: NotebookTabs },
    { label: "Meter Readings", path: "/admin/meter-readings", icon: Activity },
    { label: "Tanker Deliveries", path: "/admin/tanker-deliveries", icon: Truck },
    { label: "Employees", path: "/admin/employees", icon: Users },
    { label: "Employee Edit Dashboard", path: "/admin/employee-dashboard-editor", icon: SlidersHorizontal },
    { label: "Manager Edit Dashboard", path: "/admin/manager-dashboard-editor", icon: SlidersHorizontal },
    { label: "Leave Management", path: "/admin/leaves", icon: CalendarDays },
    { label: "Shift Schedule", path: "/admin/shifts", icon: CalendarDays },
    { label: "Task Assignments", path: "/admin/tasks", icon: ListTodo },
    { label: "Credit Customers", path: "/admin/credit-customers", icon: CreditCard },
    { label: "Expenses", path: "/admin/expenses", icon: Wallet },
    { label: "Lubricants", path: "/admin/lubricants", icon: Droplets },
    { label: "Mobile Dispenser", path: "/admin/mobile-dispenser", icon: Truck },
    { label: "Card Swipe", path: "/admin/card-swipe", icon: CreditCard },
    { label: "D.C.D", path: "/admin/dcd", icon: Receipt },
    { label: "M.D.U", path: "/admin/mdu", icon: Truck },
    { label: "Invoice Details", path: "/admin/invoice-details", icon: Receipt },
    { label: "Daily Sales", path: "/admin/daily-sales", icon: TrendingUp },
    { label: "Smart Calculator", path: "/admin/smart-calculator", icon: Calculator },
    { label: "Density Calculator", path: "/admin/density-calculator", icon: Droplets },
    { label: "TT Drivers", path: "/admin/ttdrivers", icon: Truck },
    { label: "Customer Drivers", path: "/admin/customerdrivers", icon: Truck },
    { label: "Secure Notes", path: "/admin/secure-notes", icon: FileLock2 },
    { label: "Reminder", path: "/admin/reminder", icon: Bell },
    { label: "Storage", path: "/admin/storage", icon: HardDrive },
    { label: "Settings", path: "/admin/settings", icon: Settings },
  ],
  Manager: [
    { key: "dashboard", label: "Dashboard", path: "/manager", icon: LayoutDashboard },
    { key: "approvals", label: "Approval Status", path: "/manager/approvals", icon: ClipboardCheck },
    { key: "notifications", label: "Notifications", path: "/manager/notifications", icon: Bell },
    { key: "dailyReports", label: "Daily Reports", path: "/manager/daily-reports", icon: NotebookTabs },
    { key: "meterReadings", label: "Meter Readings", path: "/manager/meter-readings", icon: Activity },
    { key: "tankerDeliveries", label: "Tanker Deliveries", path: "/manager/tanker-deliveries", icon: Truck },
    { key: "employees", label: "Employees", path: "/manager/employees", icon: Users },
    { key: "shifts", label: "Shift Schedule", path: "/manager/shifts", icon: CalendarDays },
    { key: "tasks", label: "Task Assignments", path: "/manager/tasks", icon: ListTodo },
    { key: "creditCustomers", label: "Credit Customers", path: "/manager/credit-customers", icon: CreditCard },
    { key: "expenses", label: "Expenses", path: "/manager/expenses", icon: Wallet },
    { key: "lubricants", label: "Lubricants", path: "/manager/lubricants", icon: Droplets },
    { key: "mobileDispenser", label: "Mobile Dispenser", path: "/manager/mobile-dispenser", icon: Truck },
    { key: "cardSwipe", label: "Card Swipe", path: "/manager/card-swipe", icon: CreditCard },
    { key: "dcd", label: "D.C.D", path: "/manager/dcd", icon: Receipt },
    { key: "mdu", label: "M.D.U", path: "/manager/mdu", icon: Truck },
    { key: "invoiceDetails", label: "Invoice Details", path: "/manager/invoice-details", icon: Receipt },
    { key: "dailySales", label: "Daily Sales", path: "/manager/daily-sales", icon: TrendingUp },
    { key: "smartCalculator", label: "Smart Calculator", path: "/manager/smart-calculator", icon: Calculator },
    { key: "densityCalculator", label: "Density Calculator", path: "/manager/density-calculator", icon: Droplets },
    { key: "ttDrivers", label: "TT Drivers", path: "/manager/ttdrivers", icon: Truck },
    { key: "customerDrivers", label: "Customer Drivers", path: "/manager/customerdrivers", icon: Truck },
    { key: "secureNotes", label: "Secure Notes", path: "/manager/secure-notes", icon: FileLock2 },
    { key: "reminder", label: "Reminder", path: "/manager/reminder", icon: Bell },
    { key: "settings", label: "Settings", path: "/manager/settings", icon: Settings },
  ],
  Employee: [
    { key: "overview", label: "Overview", path: "/employee", icon: LayoutDashboard },
    { key: "info", label: "My Info", path: "/employee/info", icon: Info },
    { key: "attendance", label: "My Attendance", path: "/employee/attendance", icon: UserRound },
    { key: "leaves", label: "Leave Management", path: "/employee/leaves", icon: CalendarDays },
    { key: "shifts", label: "Shift Schedule", path: "/employee/shifts", icon: CalendarDays },
    { key: "tasks", label: "My Tasks", path: "/employee/tasks", icon: ListTodo },
    { key: "expenses", label: "My Expenses", path: "/employee/expenses", icon: Receipt },
    { key: "smartCalculator", label: "Smart Calculator", path: "/employee/smart-calculator", icon: Calculator },
    { key: "densityCalculator", label: "Density Calculator", path: "/employee/density-calculator", icon: Droplets },
    { key: "lubricants", label: "My Lubricants", path: "/employee/lubricants", icon: Droplets },
    { key: "performance", label: "Performance", path: "/employee/performance", icon: TrendingUp },
    { key: "salary", label: "My Salary", path: "/employee/salary", icon: Wallet },
    { key: "dailyReport", label: "My Daily Sheet", path: "/employee/daily-report", icon: NotebookTabs },
    { key: "notifications", label: "Notifications", path: "/employee/notifications", icon: Bell },
  ],
}

export const roleBadges = {
  Admin: {
    label: "Admin HQ",
    icon: ShieldCheck,
    tone: "from-red-500/20 to-orange-500/10 text-red-300 border-red-500/30",
    dayTone: "from-[#fff8ec] via-[#ffffff] to-[#eef9e7] text-[#1f2a22] border-[#dcecc6]",
  },
  Manager: {
    label: "Manager Desk",
    icon: ClipboardCheck,
    tone: "from-blue-500/20 to-cyan-500/10 text-blue-300 border-blue-500/30",
    dayTone: "from-[#f3f8ff] via-[#ffffff] to-[#eef8f3] text-[#1b2d2b] border-[#d8e7f8]",
  },
  Employee: {
    label: "Employee Zone",
    icon: UserRound,
    tone: "from-green-500/20 to-emerald-500/10 text-green-300 border-green-500/30",
    dayTone: "from-[#eefbe4] via-[#ffffff] to-[#f7fff2] text-[#213222] border-[#d7edbf]",
  },
}
