import {
  Activity,
  CalendarDays,
  Bell,
  ClipboardCheck,
  Calculator,
  CreditCard,
  Droplets,
  FileLock2,
  HardDrive,
  Info,
  LayoutDashboard,
  ListTodo,
  NotebookTabs,
  Receipt,
  Settings,
  ShieldCheck,
  TrendingUp,
  Truck,
  UserRound,
  Users,
  Wallet,
} from "lucide-react"

export const navigationByRole = {
  Admin: [
    { label: "Dashboard", path: "/admin", icon: LayoutDashboard },
    { label: "Approvals", path: "/admin/approvals", icon: ClipboardCheck },
    { label: "Notifications", path: "/admin/notifications", icon: Bell },
    { label: "Daily Reports", path: "/admin/daily-reports", icon: NotebookTabs },
    { label: "Meter Readings", path: "/admin/meter-readings", icon: Activity },
    { label: "Tanker Deliveries", path: "/admin/tanker-deliveries", icon: Truck },
    { label: "Employees", path: "/admin/employees", icon: Users },
    { label: "Leave Management", path: "/admin/leaves", icon: CalendarDays },
    { label: "Shift Schedule", path: "/admin/shifts", icon: CalendarDays },
    { label: "Task Assignments", path: "/admin/tasks", icon: ListTodo },
    { label: "Credit Customers", path: "/admin/credit-customers", icon: CreditCard },
    { label: "Expenses", path: "/admin/expenses", icon: Wallet },
    { label: "Lubricants", path: "/admin/lubricants", icon: Droplets },
    { label: "Mobile Dispenser", path: "/admin/mobile-dispenser", icon: Truck },
    { label: "Card Swipe", path: "/admin/card-swipe", icon: CreditCard },
    { label: "Smart Calculator", path: "/admin/smart-calculator", icon: Calculator },
    { label: "TT Drivers", path: "/admin/ttdrivers", icon: Truck },
    { label: "Customer Drivers", path: "/admin/customerdrivers", icon: Truck },
    { label: "Secure Notes", path: "/admin/secure-notes", icon: FileLock2 },
    { label: "Reminder", path: "/admin/reminder", icon: Bell },
    { label: "Storage", path: "/admin/storage", icon: HardDrive },
    { label: "Settings", path: "/admin/settings", icon: Settings },
  ],
  Manager: [
    { label: "Dashboard", path: "/manager", icon: LayoutDashboard },
    { label: "Approval Status", path: "/manager/approvals", icon: ClipboardCheck },
    { label: "Notifications", path: "/manager/notifications", icon: Bell },
    { label: "Daily Reports", path: "/manager/daily-reports", icon: NotebookTabs },
    { label: "Meter Readings", path: "/manager/meter-readings", icon: Activity },
    { label: "Tanker Deliveries", path: "/manager/tanker-deliveries", icon: Truck },
    { label: "Employees", path: "/manager/employees", icon: Users },
    { label: "Shift Schedule", path: "/manager/shifts", icon: CalendarDays },
    { label: "Task Assignments", path: "/manager/tasks", icon: ListTodo },
    { label: "Credit Customers", path: "/manager/credit-customers", icon: CreditCard },
    { label: "Expenses", path: "/manager/expenses", icon: Wallet },
    { label: "Lubricants", path: "/manager/lubricants", icon: Droplets },
    { label: "Mobile Dispenser", path: "/manager/mobile-dispenser", icon: Truck },
    { label: "Card Swipe", path: "/manager/card-swipe", icon: CreditCard },
    { label: "Smart Calculator", path: "/manager/smart-calculator", icon: Calculator },
    { label: "TT Drivers", path: "/manager/ttdrivers", icon: Truck },
    { label: "Customer Drivers", path: "/manager/customerdrivers", icon: Truck },
    { label: "Secure Notes", path: "/manager/secure-notes", icon: FileLock2 },
    { label: "Reminder", path: "/manager/reminder", icon: Bell },
    { label: "Settings", path: "/manager/settings", icon: Settings },
  ],
  Employee: [
    { label: "Overview", path: "/employee", icon: LayoutDashboard },
    { label: "My Info", path: "/employee/info", icon: Info },
    { label: "My Attendance", path: "/employee/attendance", icon: UserRound },
    { label: "Leave Management", path: "/employee/leaves", icon: CalendarDays },
    { label: "Shift Schedule", path: "/employee/shifts", icon: CalendarDays },
    { label: "My Tasks", path: "/employee/tasks", icon: ListTodo },
    { label: "My Expenses", path: "/employee/expenses", icon: Receipt },
    { label: "Smart Calculator", path: "/employee/smart-calculator", icon: Calculator },
    { label: "My Lubricants", path: "/employee/lubricants", icon: Droplets },
    { label: "Performance", path: "/employee/performance", icon: TrendingUp },
    { label: "My Salary", path: "/employee/salary", icon: Wallet },
    { label: "My Daily Sheet", path: "/employee/daily-report", icon: NotebookTabs },
    { label: "Notifications", path: "/employee/notifications", icon: Bell },
  ],
}

export const roleBadges = {
  Admin: {
    label: "Admin HQ",
    icon: ShieldCheck,
    tone: "from-red-500/20 to-orange-500/10 text-red-300 border-red-500/30",
    dayTone: "from-[#fff8ec] via-[#ffffff] to-[#eef9e7] text-[#1f2a22] border-[#dcecc6]",
  },
  Manager: {
    label: "Manager Desk",
    icon: ClipboardCheck,
    tone: "from-blue-500/20 to-cyan-500/10 text-blue-300 border-blue-500/30",
    dayTone: "from-[#f3f8ff] via-[#ffffff] to-[#eef8f3] text-[#1b2d2b] border-[#d8e7f8]",
  },
  Employee: {
    label: "Employee Zone",
    icon: UserRound,
    tone: "from-green-500/20 to-emerald-500/10 text-green-300 border-green-500/30",
    dayTone: "from-[#eefbe4] via-[#ffffff] to-[#f7fff2] text-[#213222] border-[#d7edbf]",
  },
}
