import { Activity, ArrowLeft, BarChart3, CheckCircle2, CircleDollarSign, Droplets, Fuel, Gauge, RefreshCw, TrendingUp, TriangleAlert, WalletCards } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import { Area, AreaChart, Bar, BarChart, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

import { getDailySales } from "../../services/dailySaleApi"

const todayKey = () => new Date().toISOString().slice(0, 10)
const currentMonth = () => todayKey().slice(0, 7)
const numberValue = (value) => Number(value || 0)
const keyOf = (value) => String(value || "").slice(0, 10)
const monthOf = (value) => keyOf(value).slice(0, 7)
const yearOf = (value) => keyOf(value).slice(0, 4)
const getProfit = (entry) => numberValue(entry.profit ?? numberValue(entry.sale) * numberValue(entry.rate))
const colors = ["#0284c7", "#059669", "#f59e0b", "#8b5cf6"]
const chartTooltip = { backgroundColor: "var(--bg-panel)", border: "1px solid var(--border-color)", borderRadius: "12px", color: "var(--text-strong)", fontSize: "12px" }
const formatCurrency = (value) => `Rs. ${numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`
const formatNumber = (value) => numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })

function Metric({ label, value, helper, tone, icon: Icon }) {
  const styles = { blue: "border-blue-200 bg-blue-50/70 text-blue-600", green: "border-emerald-200 bg-emerald-50/70 text-emerald-600", amber: "border-amber-200 bg-amber-50/70 text-amber-600", violet: "border-violet-200 bg-violet-50/70 text-violet-600" }
  return <section className={`rounded-2xl border p-4 shadow-[var(--shadow-soft)] ${styles[tone] || styles.blue}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-[color:var(--text-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[color:var(--text-strong)]">{value}</p><p className="mt-1 text-xs font-medium text-[color:var(--text-secondary)]">{helper}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/80 shadow-sm"><Icon size={20} /></span></div></section>
}

export default function DailySalesDashboardPage() {
  const navigate = useNavigate()
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [period, setPeriod] = useState("monthly")
  const [month, setMonth] = useState(currentMonth())
  const [year, setYear] = useState(todayKey().slice(0, 4))
  const [until, setUntil] = useState(todayKey())
  const [fuel, setFuel] = useState("all")

  const load = async () => { setLoading(true); setError(""); try { const result = await getDailySales(); setEntries(Array.isArray(result) ? result : []) } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to load daily sales data.") } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const years = useMemo(() => [...new Set([todayKey().slice(0, 4), ...entries.map((entry) => yearOf(entry.date)).filter(Boolean)])].sort().reverse(), [entries])
  const filtered = useMemo(() => entries.filter((entry) => {
    const date = keyOf(entry.date)
    const matchesPeriod = period === "all" ? date <= until : period === "yearly" ? yearOf(date) === year : monthOf(date) === month
    return matchesPeriod && (fuel === "all" || String(entry.product).toUpperCase() === fuel)
  }), [entries, period, month, year, until, fuel])
  const totals = useMemo(() => filtered.reduce((sum, entry) => ({ sale: sum.sale + numberValue(entry.sale), profit: sum.profit + getProfit(entry), lossGain: sum.lossGain + numberValue(entry.lossGain), records: sum.records + 1 }), { sale: 0, profit: 0, lossGain: 0, records: 0 }), [filtered])
  const fuelData = useMemo(() => ["MS", "HSD"].map((product) => {
    const rows = filtered.filter((entry) => String(entry.product).toUpperCase() === product)
    const sale = rows.reduce((sum, entry) => sum + numberValue(entry.sale), 0)
    const profit = rows.reduce((sum, entry) => sum + getProfit(entry), 0)
    const lossGain = rows.reduce((sum, entry) => sum + numberValue(entry.lossGain), 0)
    const weightedRate = sale ? rows.reduce((sum, entry) => sum + numberValue(entry.rate) * numberValue(entry.sale), 0) / sale : 0
    return { name: product, sale, profit, lossGain, rate: weightedRate, margin: sale ? profit / sale : 0, records: rows.length }
  }), [filtered])
  const trend = useMemo(() => {
    const map = new Map()
    filtered.forEach((entry) => { const date = keyOf(entry.date); const item = map.get(date) || { date, ms: 0, hsd: 0, profit: 0, lossGain: 0, rateTotal: 0, rateQty: 0 }; const product = String(entry.product).toUpperCase(); item[product === "MS" ? "ms" : "hsd"] += numberValue(entry.sale); item.profit += getProfit(entry); item.lossGain += numberValue(entry.lossGain); item.rateTotal += numberValue(entry.rate) * numberValue(entry.sale); item.rateQty += numberValue(entry.sale); map.set(date, item) })
    return [...map.values()].sort((a, b) => a.date.localeCompare(b.date)).map((item) => ({ ...item, label: item.date.slice(8, 10), avgRate: item.rateQty ? item.rateTotal / item.rateQty : 0 }))
  }, [filtered])
  const fuelShare = fuelData.filter((item) => item.sale).map((item) => ({ name: item.name, value: item.sale }))
  const avgProfitRate = totals.sale ? totals.profit / totals.sale : 0
  const peakDay = useMemo(() => trend.slice().sort((a, b) => (b.ms + b.hsd) - (a.ms + a.hsd))[0], [trend])
  const bestMarginFuel = useMemo(() => fuelData.slice().sort((a, b) => b.margin - a.margin)[0], [fuelData])
  const salesHealth = Math.max(0, Math.min(100, Math.round(62 + Math.min(20, avgProfitRate * 5) + (totals.lossGain >= 0 ? 12 : Math.max(-18, totals.lossGain / Math.max(totals.sale, 1) * 100)))))
  const insightItems = [
    peakDay ? { label: "Peak sales day", detail: `${peakDay.date} with ${formatNumber(peakDay.ms + peakDay.hsd)} L sold`, tone: "text-sky-700 bg-sky-50 border-sky-100" } : null,
    bestMarginFuel ? { label: "Best margin fuel", detail: `${bestMarginFuel.name} at Rs. ${bestMarginFuel.margin.toFixed(2)} per L`, tone: "text-emerald-700 bg-emerald-50 border-emerald-100" } : null,
    { label: totals.lossGain >= 0 ? "Loss/gain status" : "Review needed", detail: totals.lossGain >= 0 ? `${formatNumber(totals.lossGain)} L positive gain recorded` : `${formatNumber(Math.abs(totals.lossGain))} L loss requires investigation`, tone: totals.lossGain >= 0 ? "text-violet-700 bg-violet-50 border-violet-100" : "text-rose-700 bg-rose-50 border-rose-100" },
  ].filter(Boolean)
  const selectedLabel = period === "all" ? `All data through ${until}` : period === "yearly" ? `Year ${year}` : new Date(`${month}-01T00:00:00`).toLocaleString("en-IN", { month: "long", year: "numeric" })

  return <div className="w-full p-4 text-[color:var(--text-primary)] sm:p-6">
    <section className="mb-5 overflow-hidden rounded-2xl border border-sky-200 bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-4 bg-gradient-to-r from-sky-50 via-white to-emerald-50 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-sky-600 text-gray-50 shadow-sm"><Fuel size={22} /></span><div><p className="text-[11px] font-bold uppercase tracking-wider text-sky-700">Fuel Sales Intelligence</p><h1 className="mt-1 text-2xl font-black tracking-tight text-black">Daily Sales Performance Hub</h1><p className="mt-1 text-sm text-[color:var(--text-secondary)]">See MS and HSD volume, profit, rate movement, and loss/gain health in one place.</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-color)] bg-[var(--bg-panel)] px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button><button type="button" onClick={() => navigate("/admin/daily-sales")} className="inline-flex items-center gap-2 rounded-xl bg-sky-600 px-4 py-2.5 text-sm font-semibold text-gray-50"><ArrowLeft size={16} /> Daily Sales Register</button></div></div></section>
    {error ? <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-4 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 xl:flex-row xl:items-end"><div className="flex rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-1">{[["monthly", "Monthly"], ["yearly", "Yearly"], ["all", "All Time"]].map(([value, label]) => <button key={value} onClick={() => setPeriod(value)} className={`rounded-lg px-4 py-2 text-sm font-bold ${period === value ? "bg-sky-600 text-gray-50 shadow-sm" : "text-[color:var(--text-secondary)]"}`}>{label}</button>)}</div>{period === "monthly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="input min-w-[160px]" /></label> : null}{period === "yearly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Year<select value={year} onChange={(event) => setYear(event.target.value)} className="input min-w-[130px]">{years.map((item) => <option key={item}>{item}</option>)}</select></label> : null}{period === "all" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Include records through<input type="date" value={until} onChange={(event) => setUntil(event.target.value)} className="input min-w-[180px]" /></label> : null}<label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Fuel<select value={fuel} onChange={(event) => setFuel(event.target.value)} className="input min-w-[140px]"><option value="all">MS + HSD</option><option value="MS">MS</option><option value="HSD">HSD</option></select></label><p className="text-sm font-semibold text-[color:var(--text-secondary)] xl:ml-auto">{selectedLabel}</p></div></section>
    <section className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Fuel Sold" value={`${formatNumber(totals.sale)} L`} helper={`${totals.records} sales records`} tone="blue" icon={Droplets} /><Metric label="Total Profit" value={formatCurrency(totals.profit)} helper={`Rs. ${avgProfitRate.toFixed(2)} average profit / L`} tone="green" icon={WalletCards} /><Metric label="Net Loss / Gain" value={`${formatNumber(totals.lossGain)} L`} helper={totals.lossGain >= 0 ? "Positive gain balance" : "Loss needs review"} tone="amber" icon={Gauge} /><Metric label="Best Fuel" value={fuelData.slice().sort((a, b) => b.profit - a.profit)[0]?.name || "-"} helper={formatCurrency(fuelData.slice().sort((a, b) => b.profit - a.profit)[0]?.profit)} tone="violet" icon={TrendingUp} /></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <div className="grid gap-4 md:grid-cols-2">
        {fuelData.map((item) => {
          const share = totals.sale ? (item.sale / totals.sale) * 100 : 0
          const isMs = item.name === "MS"
          return <article key={item.name} className={`overflow-hidden rounded-2xl border shadow-[var(--shadow-soft)] ${isMs ? "border-sky-200 bg-sky-50/60" : "border-emerald-200 bg-emerald-50/60"}`}>
            <div className={`flex items-center justify-between px-5 py-4 ${isMs ? "bg-sky-600" : "bg-emerald-600"}`}><div className="flex items-center gap-2 text-white"><Fuel size={19}/><span className="font-black tracking-wide">{item.name} FUEL DESK</span></div><span className="rounded-full bg-white/20 px-2.5 py-1 text-xs font-bold text-white">{share.toFixed(1)}% share</span></div>
            <div className="grid grid-cols-2 gap-4 p-5"><div><p className="text-xs font-bold uppercase tracking-wide text-[color:var(--text-muted)]">Volume</p><p className="mt-1 text-2xl font-black">{formatNumber(item.sale)} <small className="text-sm">L</small></p></div><div><p className="text-xs font-bold uppercase tracking-wide text-[color:var(--text-muted)]">Profit</p><p className="mt-1 text-2xl font-black">{formatCurrency(item.profit)}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-[color:var(--text-muted)]">Weighted Rate</p><p className="mt-1 text-lg font-black">Rs. {item.rate.toFixed(2)}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-[color:var(--text-muted)]">Profit / L</p><p className="mt-1 text-lg font-black">Rs. {item.margin.toFixed(2)}</p></div></div>
            <div className="px-5 pb-5"><div className="h-2 overflow-hidden rounded-full bg-white"><div className={`h-full rounded-full ${isMs ? "bg-sky-600" : "bg-emerald-600"}`} style={{ width: `${share}%` }}/></div></div>
          </article>
        })}
      </div>
      <article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Operations Health</p><h2 className="mt-1 text-lg font-black">Fuel performance score</h2></div><Activity className="text-violet-600" size={22}/></div><div className="mt-5 flex items-center gap-5"><div className="relative flex h-28 w-28 shrink-0 items-center justify-center rounded-full border-[12px] border-violet-100"><div className="absolute inset-[-12px] rounded-full border-[12px] border-transparent border-t-violet-600 border-r-violet-600" style={{ transform: `rotate(${Math.max(-120, Math.min(120, (salesHealth - 50) * 2.4))}deg)` }}/><span className="text-2xl font-black text-violet-700">{salesHealth}</span></div><div><p className="text-sm font-bold">{salesHealth >= 80 ? "Strong performance" : salesHealth >= 60 ? "Stable performance" : "Needs attention"}</p><p className="mt-2 text-xs leading-5 text-[color:var(--text-secondary)]">Score combines profit per litre and current loss/gain position for the selected period.</p></div></div><div className="mt-5 grid grid-cols-2 gap-2 border-t border-[var(--border-color)] pt-4"><div className="rounded-xl bg-[var(--bg-soft)] p-3"><p className="text-xs text-[color:var(--text-muted)]">Avg Profit / L</p><p className="mt-1 font-black text-emerald-700">Rs. {avgProfitRate.toFixed(2)}</p></div><div className="rounded-xl bg-[var(--bg-soft)] p-3"><p className="text-xs text-[color:var(--text-muted)]">Entries</p><p className="mt-1 font-black text-sky-700">{totals.records}</p></div></div></article>
    </section>
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4 flex items-center gap-2"><CircleDollarSign size={20} className="text-amber-600"/><div><p className="text-xs font-bold uppercase tracking-wider text-amber-600">Decision Signals</p><h2 className="mt-1 text-lg font-black">What needs attention in this period</h2></div></div><div className="grid gap-3 md:grid-cols-3">{insightItems.map((item) => <div className={`rounded-xl border p-4 ${item.tone}`} key={item.label}><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={16}/>{item.label}</div><p className="mt-2 text-sm leading-6">{item.detail}</p></div>)}</div></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-sky-600">Fuel Volume Pattern</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">MS vs HSD daily sale</h2></div><div className="h-72">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="msArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0284c7" stopOpacity=".35"/><stop offset="100%" stopColor="#0284c7" stopOpacity="0"/></linearGradient><linearGradient id="hsdArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#059669" stopOpacity=".3"/><stop offset="100%" stopColor="#059669" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={chartTooltip}/><Area type="monotone" dataKey="ms" name="MS Sale" stroke="#0284c7" fill="url(#msArea)" strokeWidth={3}/><Area type="monotone" dataKey="hsd" name="HSD Sale" stroke="#059669" fill="url(#hsdArea)" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div></div><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-2"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Fuel Mix</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Volume share</h2></div><div className="h-48">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={fuelShare} dataKey="value" nameKey="name" innerRadius={45} outerRadius={75} paddingAngle={4}>{fuelShare.map((item, index) => <Cell key={item.name} fill={colors[index]} />)}</Pie><Tooltip contentStyle={chartTooltip}/></PieChart></ResponsiveContainer>}</div><div className="space-y-2">{fuelData.map((item, index) => <div className="flex items-center justify-between text-sm" key={item.name}><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: colors[index] }}/>{item.name}</span><strong>{formatNumber(item.sale)} L</strong></div>)}</div></div></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Profit Engine</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Profit and loss/gain movement</h2></div><div className="h-64">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend}><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false}/><Tooltip contentStyle={chartTooltip} formatter={(value, name) => name === "Profit" ? formatCurrency(value) : formatNumber(value)}/><Bar yAxisId="left" dataKey="profit" name="Profit" fill="#10b981" radius={[7,7,0,0]}/><Line yAxisId="right" type="monotone" dataKey="lossGain" name="Loss / Gain" stroke="#f59e0b" strokeWidth={3}/></ComposedChart></ResponsiveContainer>}</div></div><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-amber-600">Rate Monitor</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Weighted selling rate</h2></div><div className="h-64">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="rateArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f59e0b" stopOpacity=".35"/><stop offset="100%" stopColor="#f59e0b" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={chartTooltip} formatter={(value) => `Rs. ${numberValue(value).toFixed(2)}`}/><Area type="monotone" dataKey="avgRate" name="Weighted Rate" stroke="#f59e0b" fill="url(#rateArea)" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div></div></section>
    <section className="overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-2 border-b border-[var(--border-color)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Fuel Scorecard</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">MS and HSD performance comparison</h2></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">{totals.records} records</span></div><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-sm"><thead className="bg-[var(--bg-soft)] text-left text-xs uppercase tracking-wide text-[color:var(--text-muted)]"><tr><th className="px-5 py-3">Fuel</th><th className="px-3 py-3 text-right">Volume</th><th className="px-3 py-3 text-right">Profit</th><th className="px-3 py-3 text-right">Avg Profit / L</th><th className="px-3 py-3 text-right">Weighted Rate</th><th className="px-5 py-3 text-right">Loss / Gain</th></tr></thead><tbody>{fuelData.map((item) => <tr key={item.name} className="border-t border-[var(--border-color)]"><td className="px-5 py-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.name === "MS" ? "bg-sky-100 text-sky-700" : "bg-emerald-100 text-emerald-700"}`}>{item.name}</span></td><td className="px-3 py-3 text-right font-semibold">{formatNumber(item.sale)} L</td><td className="px-3 py-3 text-right text-emerald-700">{formatCurrency(item.profit)}</td><td className="px-3 py-3 text-right">Rs. {item.margin.toFixed(2)}</td><td className="px-3 py-3 text-right">Rs. {item.rate.toFixed(2)}</td><td className={`px-5 py-3 text-right font-bold ${item.lossGain >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{formatNumber(item.lossGain)} L</td></tr>)}</tbody></table></div></section>
  </div>
}

function Loader() { return <div className="flex h-full items-center justify-center text-sm font-medium text-[color:var(--text-muted)]">Loading daily sales intelligence...</div> }
