import { ArrowLeft, ChartNoAxesCombined, CircleDollarSign, Fuel, Gauge, RefreshCw, ShieldCheck, Sparkles, TriangleAlert, TrendingDown, TrendingUp } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import { Area, AreaChart, Bar, BarChart, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

import { getDcdEntries } from "../../services/dcdApi"

const todayKey = () => new Date().toISOString().slice(0, 10)
const currentMonth = () => todayKey().slice(0, 7)
const numberValue = (value) => Number(value || 0)
const keyOf = (value) => String(value || "").slice(0, 10)
const monthOf = (value) => keyOf(value).slice(0, 7)
const yearOf = (value) => keyOf(value).slice(0, 4)
const formatNumber = (value) => numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })
const formatCurrency = (value) => `Rs. ${numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`
const tooltipStyle = { backgroundColor: "var(--bg-panel)", border: "1px solid var(--border-color)", borderRadius: "12px", color: "var(--text-strong)", fontSize: "12px" }
const palette = ["#ea580c", "#0284c7", "#8b5cf6", "#059669", "#e11d48"]
const marginOf = (entry) => numberValue(entry.salePrice) - numberValue(entry.purchasePrice)
const profitOf = (entry) => numberValue(entry.profit ?? marginOf(entry) * numberValue(entry.volume))

function Metric({ label, value, detail, tone = "orange", icon: Icon }) {
  const tones = { orange: "border-orange-200 bg-orange-50/70 text-orange-600", blue: "border-blue-200 bg-blue-50/70 text-blue-600", emerald: "border-emerald-200 bg-emerald-50/70 text-emerald-600", rose: "border-rose-200 bg-rose-50/70 text-rose-600", violet: "border-violet-200 bg-violet-50/70 text-violet-600" }
  return <article className={`rounded-2xl border p-4 shadow-[var(--shadow-soft)] ${tones[tone]}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-[color:var(--text-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[color:var(--text-strong)]">{value}</p><p className="mt-1 text-xs font-medium text-[color:var(--text-secondary)]">{detail}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/80 shadow-sm"><Icon size={20} /></span></div></article>
}

function ChartLoader() { return <div className="flex h-full items-center justify-center text-sm text-[color:var(--text-secondary)]">Loading chart...</div> }

export default function DcdDashboardPage() {
  const navigate = useNavigate()
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [period, setPeriod] = useState("monthly")
  const [month, setMonth] = useState(currentMonth())
  const [year, setYear] = useState(todayKey().slice(0, 4))
  const [until, setUntil] = useState(todayKey())
  const [product, setProduct] = useState("all")

  const load = async () => { setLoading(true); setError(""); try { const result = await getDcdEntries(); setEntries(Array.isArray(result) ? result : []) } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to load D.C.D data.") } finally { setLoading(false) } }
  useEffect(() => { load() }, [])

  const years = useMemo(() => [...new Set([todayKey().slice(0, 4), ...entries.map((entry) => yearOf(entry.date)).filter(Boolean)])].sort().reverse(), [entries])
  const products = useMemo(() => [...new Set(entries.map((entry) => String(entry.product || "").trim()).filter(Boolean))].sort(), [entries])
  const filtered = useMemo(() => entries.filter((entry) => {
    const date = keyOf(entry.date)
    const periodMatch = period === "all" ? date <= until : period === "yearly" ? yearOf(date) === year : monthOf(date) === month
    return periodMatch && (product === "all" || String(entry.product || "") === product)
  }), [entries, period, month, year, until, product])
  const ordered = useMemo(() => filtered.slice().sort((a, b) => keyOf(a.date).localeCompare(keyOf(b.date))), [filtered])
  const totals = useMemo(() => filtered.reduce((sum, entry) => ({ volume: sum.volume + numberValue(entry.volume), profit: sum.profit + profitOf(entry), purchase: sum.purchase + numberValue(entry.purchasePrice) * numberValue(entry.volume), sale: sum.sale + numberValue(entry.salePrice) * numberValue(entry.volume), records: sum.records + 1 }), { volume: 0, profit: 0, purchase: 0, sale: 0, records: 0 }), [filtered])
  const avgMargin = totals.volume ? totals.profit / totals.volume : 0
  const avgPurchase = totals.volume ? totals.purchase / totals.volume : 0
  const avgSale = totals.volume ? totals.sale / totals.volume : 0
  const profitableRows = filtered.filter((entry) => marginOf(entry) > 0).length
  const marginHealth = Math.max(0, Math.min(100, Math.round(52 + Math.min(38, Math.max(-30, avgMargin * 20)) + (filtered.length ? profitableRows / filtered.length * 10 : 0))))
  const healthLabel = marginHealth >= 85 ? "Strong margin control" : marginHealth >= 65 ? "Stable margin control" : "Margin review required"
  const productData = useMemo(() => products.map((name) => {
    const rows = filtered.filter((entry) => String(entry.product || "") === name)
    const volume = rows.reduce((sum, entry) => sum + numberValue(entry.volume), 0)
    const profit = rows.reduce((sum, entry) => sum + profitOf(entry), 0)
    const saleValue = rows.reduce((sum, entry) => sum + numberValue(entry.salePrice) * numberValue(entry.volume), 0)
    const purchaseValue = rows.reduce((sum, entry) => sum + numberValue(entry.purchasePrice) * numberValue(entry.volume), 0)
    return { name, volume, profit, margin: volume ? profit / volume : 0, saleRate: volume ? saleValue / volume : 0, purchaseRate: volume ? purchaseValue / volume : 0, records: rows.length }
  }), [filtered, products])
  const trend = useMemo(() => {
    const map = new Map()
    ordered.forEach((entry) => {
      const date = keyOf(entry.date)
      const item = map.get(date) || { date, label: date.slice(8, 10), volume: 0, profit: 0, purchaseValue: 0, saleValue: 0 }
      item.volume += numberValue(entry.volume)
      item.profit += profitOf(entry)
      item.purchaseValue += numberValue(entry.purchasePrice) * numberValue(entry.volume)
      item.saleValue += numberValue(entry.salePrice) * numberValue(entry.volume)
      map.set(date, item)
    })
    return [...map.values()].map((item) => ({ ...item, purchaseRate: item.volume ? item.purchaseValue / item.volume : 0, saleRate: item.volume ? item.saleValue / item.volume : 0, marginRate: item.volume ? item.profit / item.volume : 0 }))
  }, [ordered])
  const riskRows = useMemo(() => ordered.map((entry) => ({ ...entry, margin: marginOf(entry), profit: profitOf(entry) })).sort((a, b) => a.margin - b.margin).slice(0, 6), [ordered])
  const shiftData = useMemo(() => {
    const map = new Map()
    filtered.forEach((entry) => { const name = entry.shift?.trim() || "Unassigned"; const item = map.get(name) || { name, volume: 0, profit: 0, records: 0 }; item.volume += numberValue(entry.volume); item.profit += profitOf(entry); item.records += 1; map.set(name, item) })
    return [...map.values()].sort((a, b) => b.profit - a.profit)
  }, [filtered])
  const selectedLabel = period === "all" ? `All records through ${until}` : period === "yearly" ? `Year ${year}` : new Date(`${month}-01T00:00:00`).toLocaleString("en-IN", { month: "long", year: "numeric" })

  return <div className="w-full p-4 text-[color:var(--text-primary)] sm:p-6">
    <section className="mb-5 overflow-hidden rounded-2xl border border-orange-200 bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-4 border-l-4 border-orange-500 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-orange-500 text-gray-50 shadow-sm"><Fuel size={22} /></span><div><p className="text-[11px] font-bold uppercase tracking-wider text-orange-700">Diesel Credit Dispatch</p><h1 className="mt-1 text-2xl font-black tracking-tight text-[color:var(--text-strong)]">D.C.D Margin Command Center</h1><p className="mt-1 text-sm text-[color:var(--text-secondary)]">Watch product volume, price spread, profit quality, and shift-wise performance from one control board.</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button><button type="button" onClick={() => navigate("/admin/dcd")} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-gray-50"><ArrowLeft size={16} /> D.C.D Register</button></div></div></section>
    {error ? <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-4 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 xl:flex-row xl:items-end"><div className="flex rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-1">{[["monthly", "Monthly"], ["yearly", "Yearly"], ["all", "All Time"]].map(([value, label]) => <button key={value} type="button" onClick={() => setPeriod(value)} className={`rounded-lg px-4 py-2 text-sm font-bold ${period === value ? "bg-orange-500 text-gray-50 shadow-sm" : "text-[color:var(--text-secondary)]"}`}>{label}</button>)}</div>{period === "monthly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="input min-w-[160px]" /></label> : null}{period === "yearly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Year<select value={year} onChange={(event) => setYear(event.target.value)} className="input min-w-[130px]">{years.map((item) => <option key={item}>{item}</option>)}</select></label> : null}{period === "all" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Include records through<input type="date" value={until} onChange={(event) => setUntil(event.target.value)} className="input min-w-[180px]" /></label> : null}<label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Product<select value={product} onChange={(event) => setProduct(event.target.value)} className="input min-w-[160px]"><option value="all">All Products</option>{products.map((item) => <option key={item}>{item}</option>)}</select></label><p className="text-sm font-semibold text-[color:var(--text-secondary)] xl:ml-auto">{selectedLabel}</p></div></section>
    <section className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Dispatch Volume" value={`${formatNumber(totals.volume)} L`} detail={`${totals.records} D.C.D entries`} tone="blue" icon={Gauge} /><Metric label="Sales Value" value={formatCurrency(totals.sale)} detail={`Avg sale Rs. ${avgSale.toFixed(2)} / L`} tone="orange" icon={CircleDollarSign} /><Metric label="Total Profit" value={formatCurrency(totals.profit)} detail={`Rs. ${avgMargin.toFixed(2)} average margin / L`} tone={totals.profit >= 0 ? "emerald" : "rose"} icon={TrendingUp} /><Metric label="Purchase Value" value={formatCurrency(totals.purchase)} detail={`Avg purchase Rs. ${avgPurchase.toFixed(2)} / L`} tone="violet" icon={ChartNoAxesCombined} /></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><article className="rounded-2xl border border-orange-200 bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-700">New: Margin Health</p><h2 className="mt-1 text-xl font-black text-[color:var(--text-strong)]">{healthLabel}</h2><p className="mt-2 text-sm leading-6 text-[color:var(--text-secondary)]">The score reflects price spread and the share of profitable D.C.D entries in the selected period.</p></div><ShieldCheck className="text-orange-500" size={26}/></div><div className="mt-6 flex items-center gap-5"><div className="relative flex h-28 w-28 shrink-0 items-center justify-center rounded-full border-[12px] border-orange-100"><div className="absolute inset-[-12px] rounded-full border-[12px] border-transparent border-t-orange-500 border-r-orange-500" style={{ transform: `rotate(${Math.max(-118, Math.min(118, (marginHealth - 50) * 2.35))}deg)` }} /><span className="text-2xl font-black text-orange-600">{marginHealth}</span></div><div className="space-y-2 text-sm"><p><span className="text-[color:var(--text-muted)]">Positive entries:</span> <strong>{profitableRows}/{filtered.length}</strong></p><p><span className="text-[color:var(--text-muted)]">Average margin:</span> <strong>Rs. {avgMargin.toFixed(2)}/L</strong></p><p><span className="text-[color:var(--text-muted)]">Margin value:</span> <strong>{formatCurrency(totals.profit)}</strong></p></div></div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-sky-700">New: Product Mix Control</p><h2 className="mt-1 text-xl font-black text-[color:var(--text-strong)]">Volume and profit by product</h2></div><Sparkles className="text-sky-600" size={24}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{productData.map((item, index) => <div key={item.name} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-4"><div className="flex items-center justify-between"><strong style={{ color: palette[index % palette.length] }}>{item.name}</strong><span className="text-xs font-bold text-[color:var(--text-secondary)]">{totals.volume ? ((item.volume / totals.volume) * 100).toFixed(1) : 0}% volume</span></div><p className="mt-2 text-xl font-black">{formatNumber(item.volume)} L</p><p className="mt-1 text-xs text-[color:var(--text-secondary)]">Profit {formatCurrency(item.profit)} · Margin Rs. {item.margin.toFixed(2)}/L</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full" style={{ background: palette[index % palette.length], width: `${totals.volume ? (item.volume / totals.volume) * 100 : 0}%` }} /></div></div>)}</div></article></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Dispatch Rhythm</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Daily volume and profit movement</h2></div><div className="h-72">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend}><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => name === "Profit" ? formatCurrency(value) : formatNumber(value)} /><Bar yAxisId="left" dataKey="volume" name="Volume" fill="#0284c7" radius={[7,7,0,0]}/><Line yAxisId="right" type="monotone" dataKey="profit" name="Profit" stroke="#ea580c" strokeWidth={3}/></ComposedChart></ResponsiveContainer>}</div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-2"><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Product Share</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Dispatch volume split</h2></div><div className="h-48">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={productData.filter((item) => item.volume)} dataKey="volume" nameKey="name" innerRadius={45} outerRadius={76} paddingAngle={5}>{productData.filter((item) => item.volume).map((item, index) => <Cell key={item.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer>}</div><div className="space-y-2">{productData.map((item, index) => <div className="flex items-center justify-between text-sm" key={item.name}><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: palette[index % palette.length] }} />{item.name}</span><strong>{formatNumber(item.volume)} L</strong></div>)}</div></article></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Price Spread</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Purchase versus sale price</h2></div><div className="h-64">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="dcdPurchase" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#e11d48" stopOpacity=".28"/><stop offset="100%" stopColor="#e11d48" stopOpacity="0"/></linearGradient><linearGradient id="dcdSale" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity=".28"/><stop offset="100%" stopColor="#10b981" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => `Rs. ${numberValue(value).toFixed(2)}`} /><Area type="monotone" dataKey="purchaseRate" name="Purchase Price" stroke="#e11d48" fill="url(#dcdPurchase)" strokeWidth={3}/><Area type="monotone" dataKey="saleRate" name="Sale Price" stroke="#10b981" fill="url(#dcdSale)" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Shift Performance</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Profit contribution by shift</h2></div><div className="h-64">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><BarChart data={shiftData} layout="vertical" margin={{ left: 12 }}><XAxis type="number" tickLine={false} axisLine={false}/><YAxis type="category" dataKey="name" width={75} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => formatCurrency(value)} /><Bar dataKey="profit" name="Profit" radius={[0,7,7,0]}>{shiftData.map((item, index) => <Cell key={item.name} fill={palette[index % palette.length]} />)}</Bar></BarChart></ResponsiveContainer>}</div></article></section>
    <section className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-rose-700">New: Price Risk Watchlist</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Entries with the lowest margin per litre</h2></div><TriangleAlert className="text-rose-600" size={22}/></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-[var(--border-color)] text-xs uppercase tracking-wider text-[color:var(--text-muted)]"><tr><th className="px-3 py-3">Date</th><th className="px-3 py-3">Product</th><th className="px-3 py-3 text-right">Volume</th><th className="px-3 py-3 text-right">Purchase</th><th className="px-3 py-3 text-right">Sale</th><th className="px-3 py-3 text-right">Margin</th><th className="px-3 py-3 text-right">Profit</th></tr></thead><tbody>{riskRows.length ? riskRows.map((entry) => <tr key={entry._id || `${entry.date}-${entry.product}-${entry.volume}`} className="border-b border-[var(--border-color)] last:border-0"><td className="px-3 py-3 font-semibold">{keyOf(entry.date)}</td><td className="px-3 py-3">{entry.product || "-"}</td><td className="px-3 py-3 text-right">{formatNumber(entry.volume)} L</td><td className="px-3 py-3 text-right">Rs. {numberValue(entry.purchasePrice).toFixed(2)}</td><td className="px-3 py-3 text-right">Rs. {numberValue(entry.salePrice).toFixed(2)}</td><td className={`px-3 py-3 text-right font-black ${entry.margin < 0 ? "text-rose-600" : "text-emerald-600"}`}>Rs. {entry.margin.toFixed(2)}</td><td className={`px-3 py-3 text-right font-bold ${entry.profit < 0 ? "text-rose-600" : "text-emerald-600"}`}>{formatCurrency(entry.profit)}</td></tr>) : <tr><td colSpan="7" className="px-3 py-10 text-center text-[color:var(--text-secondary)]">No D.C.D entries in this period.</td></tr>}</tbody></table></div></section>
  </div>
}
