import { ArrowLeft, BadgeIndianRupee, Boxes, ChartNoAxesCombined, CircleDollarSign, Fuel, RefreshCw, Route, ShieldCheck, TriangleAlert, TrendingDown, TrendingUp, Truck } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import { Area, AreaChart, Bar, BarChart, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"

import { getInvoiceDetails } from "../../services/invoiceDetailApi"

const todayKey = () => new Date().toISOString().slice(0, 10)
const currentMonth = () => todayKey().slice(0, 7)
const numberValue = (value) => Number(value || 0)
const keyOf = (value) => String(value || "").slice(0, 10)
const monthOf = (value) => keyOf(value).slice(0, 7)
const yearOf = (value) => keyOf(value).slice(0, 4)
const formatNumber = (value) => numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })
const formatCurrency = (value) => `Rs. ${numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`
const tooltipStyle = { backgroundColor: "var(--bg-panel)", border: "1px solid var(--border-color)", borderRadius: "12px", color: "var(--text-strong)", fontSize: "12px" }
const fuelColors = { MS: "#2563eb", HSD: "#f59e0b" }

const lfrAmountOf = (entry) => numberValue(entry.qty) * numberValue(entry.lfr)
const purchaseOf = (entry) => numberValue(entry.purchaseAmount ?? (numberValue(entry.qty) ? (numberValue(entry.invoiceAmount) + numberValue(entry.transportCost)) / numberValue(entry.qty) + numberValue(entry.lfr) : 0))
const marginOf = (entry) => numberValue(entry.rsp) - purchaseOf(entry)

function Metric({ label, value, detail, tone = "blue", icon: Icon }) {
  const tones = { blue: "border-blue-200 bg-blue-50/70 text-blue-600", amber: "border-amber-200 bg-amber-50/70 text-amber-600", emerald: "border-emerald-200 bg-emerald-50/70 text-emerald-600", rose: "border-rose-200 bg-rose-50/70 text-rose-600", violet: "border-violet-200 bg-violet-50/70 text-violet-600" }
  return <article className={`rounded-2xl border p-4 shadow-[var(--shadow-soft)] ${tones[tone]}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-[color:var(--text-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[color:var(--text-strong)]">{value}</p><p className="mt-1 text-xs font-medium text-[color:var(--text-secondary)]">{detail}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/80 shadow-sm"><Icon size={20} /></span></div></article>
}

function ChartLoader() { return <div className="flex h-full items-center justify-center text-sm text-[color:var(--text-secondary)]">Loading chart...</div> }

export default function InvoiceDetailsDashboardPage() {
  const navigate = useNavigate()
  const [entries, setEntries] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [period, setPeriod] = useState("monthly")
  const [month, setMonth] = useState(currentMonth())
  const [year, setYear] = useState(todayKey().slice(0, 4))
  const [until, setUntil] = useState(todayKey())
  const [fuel, setFuel] = useState("all")

  const load = async () => { setLoading(true); setError(""); try { const result = await getInvoiceDetails(); setEntries(Array.isArray(result) ? result : []) } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to load invoice details.") } finally { setLoading(false) } }
  useEffect(() => { load() }, [])

  const years = useMemo(() => [...new Set([todayKey().slice(0, 4), ...entries.map((entry) => yearOf(entry.date)).filter(Boolean)])].sort().reverse(), [entries])
  const filtered = useMemo(() => entries.filter((entry) => {
    const date = keyOf(entry.date)
    const periodMatch = period === "all" ? date <= until : period === "yearly" ? yearOf(date) === year : monthOf(date) === month
    const fuelMatch = fuel === "all" || String(entry.product || "").toUpperCase() === fuel
    return periodMatch && fuelMatch
  }), [entries, period, month, year, until, fuel])
  const ordered = useMemo(() => filtered.slice().sort((a, b) => keyOf(a.date).localeCompare(keyOf(b.date))), [filtered])
  const totals = useMemo(() => filtered.reduce((sum, entry) => ({ qty: sum.qty + numberValue(entry.qty), invoice: sum.invoice + numberValue(entry.invoiceAmount), transport: sum.transport + numberValue(entry.transportCost), lfrAmount: sum.lfrAmount + lfrAmountOf(entry), marginValue: sum.marginValue + marginOf(entry) * numberValue(entry.qty), records: sum.records + 1 }), { qty: 0, invoice: 0, transport: 0, lfrAmount: 0, marginValue: 0, records: 0 }), [filtered])
  const fuelData = useMemo(() => ["MS", "HSD"].map((product) => {
    const rows = filtered.filter((entry) => String(entry.product || "").toUpperCase() === product)
    const qty = rows.reduce((sum, entry) => sum + numberValue(entry.qty), 0)
    const invoice = rows.reduce((sum, entry) => sum + numberValue(entry.invoiceAmount), 0)
    const transport = rows.reduce((sum, entry) => sum + numberValue(entry.transportCost), 0)
    const lfrAmount = rows.reduce((sum, entry) => sum + lfrAmountOf(entry), 0)
    const rspValue = rows.reduce((sum, entry) => sum + numberValue(entry.rsp) * numberValue(entry.qty), 0)
    const purchaseRate = qty ? (invoice + transport + lfrAmount) / qty : 0
    const rsp = qty ? rspValue / qty : 0
    return { name: product, qty, invoice, transport, lfrAmount, purchaseRate, rsp, margin: rsp - purchaseRate, records: rows.length }
  }), [filtered])
  const avgPurchase = totals.qty ? (totals.invoice + totals.transport + totals.lfrAmount) / totals.qty : 0
  const transportPerLitre = totals.qty ? totals.transport / totals.qty : 0
  const avgMargin = totals.qty ? totals.marginValue / totals.qty : 0
  const costHealth = Math.max(0, Math.min(100, Math.round(68 + Math.max(-25, avgMargin * 11) - Math.min(20, transportPerLitre * 2) - filtered.filter((entry) => marginOf(entry) < 0).length * 4)))
  const healthLabel = costHealth >= 86 ? "Cost position is strong" : costHealth >= 65 ? "Cost position is stable" : "Cost review needed"
  const trend = useMemo(() => {
    const map = new Map()
    ordered.forEach((entry) => {
      const date = keyOf(entry.date)
      const item = map.get(date) || { date, label: date.slice(8, 10), msQty: 0, hsdQty: 0, invoice: 0, transport: 0, lfrAmount: 0, marginValue: 0, purchaseValue: 0, qty: 0 }
      const product = String(entry.product || "").toUpperCase()
      item[product === "MS" ? "msQty" : "hsdQty"] += numberValue(entry.qty)
      item.invoice += numberValue(entry.invoiceAmount)
      item.transport += numberValue(entry.transportCost)
      item.lfrAmount += lfrAmountOf(entry)
      item.marginValue += marginOf(entry) * numberValue(entry.qty)
      item.purchaseValue += purchaseOf(entry) * numberValue(entry.qty)
      item.qty += numberValue(entry.qty)
      map.set(date, item)
    })
    return [...map.values()].map((item) => ({ ...item, purchaseRate: item.qty ? item.purchaseValue / item.qty : 0, marginRate: item.qty ? item.marginValue / item.qty : 0, transportRate: item.qty ? item.transport / item.qty : 0 }))
  }, [ordered])
  const marginWatchlist = useMemo(() => ordered.map((entry) => ({ ...entry, margin: marginOf(entry), purchase: purchaseOf(entry), transportRate: numberValue(entry.qty) ? numberValue(entry.transportCost) / numberValue(entry.qty) : 0 })).sort((a, b) => a.margin - b.margin).slice(0, 6), [ordered])
  const transportQueue = useMemo(() => ordered.map((entry) => ({ ...entry, transportRate: numberValue(entry.qty) ? numberValue(entry.transportCost) / numberValue(entry.qty) : 0 })).sort((a, b) => b.transportRate - a.transportRate).slice(0, 5), [ordered])
  const quantityShare = fuelData.filter((item) => item.qty).map((item) => ({ name: item.name, value: item.qty }))
  const selectedLabel = period === "all" ? `All records through ${until}` : period === "yearly" ? `Year ${year}` : new Date(`${month}-01T00:00:00`).toLocaleString("en-IN", { month: "long", year: "numeric" })

  return <div className="w-full p-4 text-[color:var(--text-primary)] sm:p-6">
    <section className="mb-5 overflow-hidden rounded-2xl border border-violet-200 bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-4 border-l-4 border-violet-600 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-600 text-gray-50 shadow-sm"><ChartNoAxesCombined size={22} /></span><div><p className="text-[11px] font-bold uppercase tracking-wider text-violet-700">Purchase & Margin Intelligence</p><h1 className="mt-1 text-2xl font-black tracking-tight text-[color:var(--text-strong)]">Invoice Operations Command</h1><p className="mt-1 text-sm text-[color:var(--text-secondary)]">Control fuel buying cost, transport efficiency, LFR exposure, and MS/HSD margins in one view.</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button><button type="button" onClick={() => navigate("/admin/invoice-details")} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-gray-50"><ArrowLeft size={16} /> Invoice Register</button></div></div></section>
    {error ? <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-4 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 xl:flex-row xl:items-end"><div className="flex rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-1">{[["monthly", "Monthly"], ["yearly", "Yearly"], ["all", "All Time"]].map(([value, label]) => <button key={value} type="button" onClick={() => setPeriod(value)} className={`rounded-lg px-4 py-2 text-sm font-bold ${period === value ? "bg-violet-600 text-gray-50 shadow-sm" : "text-[color:var(--text-secondary)]"}`}>{label}</button>)}</div>{period === "monthly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="input min-w-[160px]" /></label> : null}{period === "yearly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Year<select value={year} onChange={(event) => setYear(event.target.value)} className="input min-w-[130px]">{years.map((item) => <option key={item}>{item}</option>)}</select></label> : null}{period === "all" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Include records through<input type="date" value={until} onChange={(event) => setUntil(event.target.value)} className="input min-w-[180px]" /></label> : null}<label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Product<select value={fuel} onChange={(event) => setFuel(event.target.value)} className="input min-w-[140px]"><option value="all">MS + HSD</option><option value="MS">MS</option><option value="HSD">HSD</option></select></label><p className="text-sm font-semibold text-[color:var(--text-secondary)] xl:ml-auto">{selectedLabel}</p></div></section>
    <section className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Invoice Value" value={formatCurrency(totals.invoice)} detail={`${totals.records} invoice entries`} tone="violet" icon={BadgeIndianRupee} /><Metric label="Fuel Quantity" value={`${formatNumber(totals.qty)} L`} detail="MS and HSD combined" tone="blue" icon={Fuel} /><Metric label="LFR Amount" value={formatCurrency(totals.lfrAmount)} detail="Quantity multiplied by LFR" tone="amber" icon={CircleDollarSign} /><Metric label="Margin Value" value={formatCurrency(totals.marginValue)} detail={`Rs. ${avgMargin.toFixed(2)} average per L`} tone={totals.marginValue >= 0 ? "emerald" : "rose"} icon={TrendingUp} /></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><article className="rounded-2xl border border-violet-200 bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-violet-700">New: Purchase Cost Health</p><h2 className="mt-1 text-xl font-black text-[color:var(--text-strong)]">{healthLabel}</h2><p className="mt-2 text-sm leading-6 text-[color:var(--text-secondary)]">Score combines purchase margin, transport per litre, and below-zero margin entries.</p></div><ShieldCheck className="text-violet-600" size={26}/></div><div className="mt-6 flex items-center gap-5"><div className="relative flex h-28 w-28 shrink-0 items-center justify-center rounded-full border-[12px] border-violet-100"><div className="absolute inset-[-12px] rounded-full border-[12px] border-transparent border-t-violet-600 border-r-violet-600" style={{ transform: `rotate(${Math.max(-118, Math.min(118, (costHealth - 50) * 2.35))}deg)` }} /><span className="text-2xl font-black text-violet-700">{costHealth}</span></div><div className="space-y-2 text-sm"><p><span className="text-[color:var(--text-muted)]">Avg purchase:</span> <strong>Rs. {avgPurchase.toFixed(2)}</strong></p><p><span className="text-[color:var(--text-muted)]">Avg transport/L:</span> <strong>Rs. {transportPerLitre.toFixed(2)}</strong></p><p><span className="text-[color:var(--text-muted)]">Low-margin rows:</span> <strong>{filtered.filter((entry) => marginOf(entry) < 0).length}</strong></p></div></div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">New: Quantity Mix Planner</p><h2 className="mt-1 text-xl font-black text-[color:var(--text-strong)]">MS and HSD buying split</h2></div><Boxes className="text-blue-600" size={24}/></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{fuelData.map((item) => <div key={item.name} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-4"><div className="flex items-center justify-between"><span className="font-black" style={{ color: fuelColors[item.name] }}>{item.name}</span><span className="text-xs font-bold text-[color:var(--text-secondary)]">{totals.qty ? ((item.qty / totals.qty) * 100).toFixed(1) : 0}% mix</span></div><p className="mt-2 text-xl font-black">{formatNumber(item.qty)} L</p><p className="mt-1 text-xs text-[color:var(--text-secondary)]">Purchase Rs. {item.purchaseRate.toFixed(2)} · Margin Rs. {item.margin.toFixed(2)}/L</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full" style={{ background: fuelColors[item.name], width: `${totals.qty ? (item.qty / totals.qty) * 100 : 0}%` }} /></div></div>)}</div></article></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Invoice Flow</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">MS and HSD quantity received</h2></div><div className="h-72">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="invoiceMs" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".35"/><stop offset="100%" stopColor="#2563eb" stopOpacity="0"/></linearGradient><linearGradient id="invoiceHsd" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f59e0b" stopOpacity=".35"/><stop offset="100%" stopColor="#f59e0b" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="msQty" name="MS Qty" stroke="#2563eb" fill="url(#invoiceMs)" strokeWidth={3}/><Area type="monotone" dataKey="hsdQty" name="HSD Qty" stroke="#f59e0b" fill="url(#invoiceHsd)" strokeWidth={3}/></AreaChart></ResponsiveContainer>}</div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-2"><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Quantity Mix</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Fuel volume share</h2></div><div className="h-48">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={quantityShare} dataKey="value" nameKey="name" innerRadius={45} outerRadius={76} paddingAngle={5}>{quantityShare.map((item) => <Cell key={item.name} fill={fuelColors[item.name]} />)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer>}</div><div className="space-y-2">{fuelData.map((item) => <div className="flex items-center justify-between text-sm" key={item.name}><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: fuelColors[item.name] }} />{item.name}</span><strong>{formatNumber(item.qty)} L</strong></div>)}</div></article></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Purchase vs Margin</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Rate movement by invoice date</h2></div><div className="h-64">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><ComposedChart data={trend}><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => name === "Margin / L" || name === "Purchase Rate" ? `Rs. ${numberValue(value).toFixed(2)}` : formatCurrency(value)} /><Bar yAxisId="left" dataKey="marginValue" name="Margin Value" fill="#10b981" radius={[7,7,0,0]}/><Line yAxisId="right" type="monotone" dataKey="purchaseRate" name="Purchase Rate" stroke="#7c3aed" strokeWidth={3}/><Line yAxisId="right" type="monotone" dataKey="marginRate" name="Margin / L" stroke="#f59e0b" strokeWidth={3}/></ComposedChart></ResponsiveContainer>}</div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-sky-700">New: Transport Efficiency</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Transport cost per litre</h2></div><div className="h-64">{loading ? <ChartLoader /> : <ResponsiveContainer width="100%" height="100%"><BarChart data={trend}><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(value) => `Rs. ${numberValue(value).toFixed(2)}`} /><Bar dataKey="transportRate" name="Transport / L" fill="#0ea5e9" radius={[7,7,0,0]} /></BarChart></ResponsiveContainer>}</div></article></section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-rose-700">New: Margin Watchlist</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Lowest purchase margins</h2></div><TriangleAlert className="text-rose-600" size={22}/></div><div className="max-h-72 overflow-y-auto pr-1">{marginWatchlist.length ? marginWatchlist.map((entry) => <div key={entry._id || `${entry.date}-${entry.product}-${entry.qty}`} className="grid grid-cols-[auto_1fr_auto] items-center gap-3 border-b border-[var(--border-color)] py-3 last:border-0"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${entry.margin < 0 ? "bg-rose-50 text-rose-600" : "bg-emerald-50 text-emerald-600"}`}>{entry.margin < 0 ? <TrendingDown size={18}/> : <TrendingUp size={18}/>}</span><div><p className="font-bold text-[color:var(--text-strong)]">{entry.product} · {keyOf(entry.date)} · {formatNumber(entry.qty)} L</p><p className="mt-1 text-xs text-[color:var(--text-secondary)]">Purchase Rs. {entry.purchase.toFixed(2)} · RSP Rs. {numberValue(entry.rsp).toFixed(2)}</p></div><strong className={entry.margin < 0 ? "text-rose-600" : "text-emerald-600"}>Rs. {entry.margin.toFixed(2)}</strong></div>) : <p className="py-8 text-center text-sm text-[color:var(--text-secondary)]">No invoice data in this period.</p>}</div></article><article className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-700">Transport Review Queue</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Highest transport cost entries</h2></div><Truck className="text-amber-600" size={22}/></div><div className="space-y-3">{transportQueue.length ? transportQueue.map((entry) => <div key={entry._id || `${entry.date}-${entry.product}-${entry.qty}`} className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-3"><div className="flex items-center justify-between gap-3"><strong>{entry.product} · {keyOf(entry.date)}</strong><span className="font-black text-amber-700">Rs. {entry.transportRate.toFixed(2)} / L</span></div><div className="mt-2 flex justify-between text-xs text-[color:var(--text-secondary)]"><span>{formatNumber(entry.qty)} L received</span><span>Transport {formatCurrency(entry.transportCost)}</span></div></div>) : <p className="py-8 text-center text-sm text-[color:var(--text-secondary)]">No transport data in this period.</p>}</div></article></section>
  </div>
}
