import { ArrowLeft, Boxes, CircleDollarSign, PackageCheck, RefreshCw, ShoppingBag, TriangleAlert, Trophy } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { useNavigate } from "react-router-dom"
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis, PolarGrid, PolarAngleAxis } from "recharts"

import { getLubricants, getProducts } from "../../services/lubricantApi"

const todayKey = () => new Date().toISOString().slice(0, 10)
const currentMonth = () => todayKey().slice(0, 7)
const numberValue = (value) => Number(value || 0)
const keyOf = (value) => String(value || "").slice(0, 10)
const monthOf = (value) => keyOf(value).slice(0, 7)
const yearOf = (value) => keyOf(value).slice(0, 4)
const colors = ["#f59e0b", "#14b8a6", "#2563eb", "#8b5cf6", "#ec4899", "#84cc16"]
const tooltip = { backgroundColor: "var(--bg-panel)", border: "1px solid var(--border-color)", borderRadius: "12px", color: "var(--text-strong)", fontSize: "12px" }
const formatCurrency = (value) => `Rs. ${numberValue(value).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`

function Metric({ label, value, helper, tone, icon: Icon }) {
  const tones = { amber: "border-amber-200 bg-amber-50/70 text-amber-600", emerald: "border-emerald-200 bg-emerald-50/70 text-emerald-600", blue: "border-blue-200 bg-blue-50/70 text-blue-600", rose: "border-rose-200 bg-rose-50/70 text-rose-600" }
  return <section className={`rounded-2xl border p-4 shadow-[var(--shadow-soft)] ${tones[tone] || tones.amber}`}><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-[color:var(--text-muted)]">{label}</p><p className="mt-2 text-2xl font-black text-[color:var(--text-strong)]">{value}</p><p className="mt-1 text-xs font-medium text-[color:var(--text-secondary)]">{helper}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/75 shadow-sm"><Icon size={20} /></span></div></section>
}

export default function LubricantDashboardPage() {
  const navigate = useNavigate()
  const [sales, setSales] = useState([])
  const [products, setProducts] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [mode, setMode] = useState("monthly")
  const [month, setMonth] = useState(currentMonth())
  const [year, setYear] = useState(todayKey().slice(0, 4))
  const [until, setUntil] = useState(todayKey())
  const [productFilter, setProductFilter] = useState("all")

  const loadData = async () => {
    setLoading(true); setError("")
    try {
      const [saleResponse, productResponse] = await Promise.all([getLubricants(), getProducts()])
      setSales(Array.isArray(saleResponse) ? saleResponse : [])
      setProducts(Array.isArray(productResponse) ? productResponse : [])
    } catch (requestError) { setError(requestError?.response?.data?.message || "Unable to load lubricant data.") } finally { setLoading(false) }
  }
  useEffect(() => { loadData() }, [])

  const years = useMemo(() => [...new Set([todayKey().slice(0, 4), ...sales.map((sale) => yearOf(sale.date)).filter(Boolean)])].sort().reverse(), [sales])
  const filteredSales = useMemo(() => sales.filter((sale) => {
    const date = keyOf(sale.date)
    const period = mode === "all" ? date <= until : mode === "yearly" ? yearOf(date) === year : monthOf(date) === month
    return period && (productFilter === "all" || sale.product === productFilter)
  }), [sales, mode, month, year, until, productFilter])
  const totals = useMemo(() => filteredSales.reduce((result, sale) => ({ revenue: result.revenue + numberValue(sale.total), profit: result.profit + numberValue(sale.totalProfit), qty: result.qty + numberValue(sale.quantity), orders: result.orders + 1 }), { revenue: 0, profit: 0, qty: 0, orders: 0 }), [filteredSales])
  const productRows = useMemo(() => products.map((product) => {
    const productSales = filteredSales.filter((sale) => sale.product === product.name)
    const quantity = productSales.reduce((total, sale) => total + numberValue(sale.quantity), 0)
    const revenue = productSales.reduce((total, sale) => total + numberValue(sale.total), 0)
    const profit = productSales.reduce((total, sale) => total + numberValue(sale.totalProfit), 0)
    const stock = numberValue(product.stock)
    const marginPerUnit = numberValue(product.price) - numberValue(product.costPrice)
    return { ...product, quantity, revenue, profit, stock, marginPerUnit, marginPercent: product.price ? (marginPerUnit / numberValue(product.price)) * 100 : 0, coverage: quantity ? stock / quantity : null }
  }).sort((a, b) => b.profit - a.profit), [products, filteredSales])
  const inventoryValue = useMemo(() => products.reduce((sum, product) => sum + numberValue(product.stock) * numberValue(product.costPrice), 0), [products])
  const lowStock = productRows.filter((product) => product.stock <= 5)
  const marginRate = totals.revenue ? (totals.profit / totals.revenue) * 100 : 0
  const dailyTrend = useMemo(() => {
    const map = new Map()
    filteredSales.forEach((sale) => { const date = keyOf(sale.date); const item = map.get(date) || { date, revenue: 0, profit: 0, quantity: 0 }; item.revenue += numberValue(sale.total); item.profit += numberValue(sale.totalProfit); item.quantity += numberValue(sale.quantity); map.set(date, item) })
    return [...map.values()].sort((a, b) => a.date.localeCompare(b.date)).map((item) => ({ ...item, label: item.date.slice(8, 10) }))
  }, [filteredSales])
  const topProducts = productRows.filter((product) => product.revenue || product.stock).slice(0, 6)
  const pieData = productRows.filter((product) => product.revenue > 0).slice(0, 6).map((product) => ({ name: product.name, value: product.revenue }))
  const periodLabel = mode === "all" ? `All records through ${until}` : mode === "yearly" ? `Year ${year}` : new Date(`${month}-01T00:00:00`).toLocaleString("en-IN", { month: "long", year: "numeric" })

  return <div className="w-full p-4 text-[color:var(--text-primary)] sm:p-6">
    <section className="mb-5 overflow-hidden rounded-2xl border border-amber-200 bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-4 bg-gradient-to-r from-amber-50 via-white to-emerald-50 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-500 text-gray-50 shadow-sm"><ShoppingBag size={22} /></span><div><p className="text-[11px] font-bold uppercase tracking-wider text-amber-700">Lubricant Intelligence</p><h1 className="mt-1 text-2xl font-black tracking-tight text-black">Lubricant Command Deck</h1><p className="mt-1 text-sm text-[color:var(--text-secondary)]">Sales velocity, product margins, inventory cover, and stock risks in one view.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={loadData} className="inline-flex items-center gap-2 rounded-xl border border-[var(--border-color)] bg-[var(--bg-panel)] px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16} /> Refresh</button><button onClick={() => navigate("/admin/lubricants")} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-semibold text-white"><ArrowLeft size={16} /> Lubricant Sales</button></div></div></section>
    {error ? <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</div> : null}
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-4 shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-3 xl:flex-row xl:items-end"><div className="flex rounded-xl border border-[var(--border-color)] bg-[var(--bg-soft)] p-1">{[["monthly", "Monthly"], ["yearly", "Yearly"], ["all", "All Time"]].map(([value, label]) => <button key={value} onClick={() => setMode(value)} className={`rounded-lg px-4 py-2 text-sm font-bold ${mode === value ? "bg-amber-500 text-white shadow-sm" : "text-[color:var(--text-secondary)]"}`}>{label}</button>)}</div>{mode === "monthly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Month<input type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="input min-w-[160px]" /></label> : null}{mode === "yearly" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Year<select value={year} onChange={(event) => setYear(event.target.value)} className="input min-w-[130px]">{years.map((item) => <option key={item}>{item}</option>)}</select></label> : null}{mode === "all" ? <label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Include records through<input type="date" value={until} onChange={(event) => setUntil(event.target.value)} className="input min-w-[180px]" /></label> : null}<label className="grid gap-1 text-xs font-semibold text-[color:var(--text-muted)]">Product<select value={productFilter} onChange={(event) => setProductFilter(event.target.value)} className="input min-w-[180px]"><option value="all">All Products</option>{products.map((product) => <option key={product._id || product.name} value={product.name}>{product.name}</option>)}</select></label><p className="text-sm font-semibold text-[color:var(--text-secondary)] xl:ml-auto">{periodLabel}</p></div></section>
    <section className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Sales Revenue" value={formatCurrency(totals.revenue)} helper={`${totals.orders} sale entries`} tone="amber" icon={CircleDollarSign} /><Metric label="Gross Profit" value={formatCurrency(totals.profit)} helper={`${marginRate.toFixed(1)}% overall margin`} tone="emerald" icon={Trophy} /><Metric label="Units Sold" value={totals.qty.toLocaleString("en-IN")} helper="Selected period sales velocity" tone="blue" icon={PackageCheck} /><Metric label="Inventory Value" value={formatCurrency(inventoryValue)} helper={`${lowStock.length} product${lowStock.length === 1 ? "" : "s"} low in stock`} tone="rose" icon={Boxes} /></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-amber-600">Sales Velocity</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Revenue and profit movement</h2></div><div className="h-72">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={dailyTrend}><defs><linearGradient id="salesFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#f59e0b" stopOpacity=".35" /><stop offset="100%" stopColor="#f59e0b" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `${Math.round(value / 1000)}k`} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltip} formatter={(value) => formatCurrency(value)} /><Area type="monotone" dataKey="revenue" name="Revenue" stroke="#f59e0b" strokeWidth={3} fill="url(#salesFill)" /><Area type="monotone" dataKey="profit" name="Profit" stroke="#059669" strokeWidth={2.5} fill="transparent" /></AreaChart></ResponsiveContainer>}</div></div><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-2"><p className="text-xs font-bold uppercase tracking-wider text-rose-600">Stock Watch</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Low-stock alerts</h2></div>{lowStock.length ? <div className="space-y-3">{lowStock.map((product) => <div key={product._id || product.name} className="rounded-xl border border-rose-100 bg-rose-50 p-3"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-2 font-bold"><TriangleAlert size={16} className="text-rose-600" />{product.name}</span><strong className="text-rose-700">{product.stock} left</strong></div><p className="mt-1 text-xs text-rose-700">Sold {product.quantity} in this period. Reorder consideration recommended.</p></div>)}</div> : <div className="mt-6 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">All listed products are above the low-stock threshold.</div>}</div></section>
    <section className="mb-5 grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)] xl:col-span-2"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Product Momentum</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Sales, profit and margin shape</h2></div><div className="h-80">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><RadarChart data={topProducts}><PolarGrid /><PolarAngleAxis dataKey="name" tick={{ fontSize: 11 }} /><Radar dataKey="quantity" name="Units Sold" stroke="#2563eb" fill="#2563eb" fillOpacity={.22} /><Radar dataKey="marginPercent" name="Margin %" stroke="#f59e0b" fill="#f59e0b" fillOpacity={.18} /><Tooltip contentStyle={tooltip} /></RadarChart></ResponsiveContainer>}</div></div><div className="rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-3"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Revenue Share</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Top product mix</h2></div><div className="h-48">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius={43} outerRadius={73} paddingAngle={3}>{pieData.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tooltip} formatter={(value) => formatCurrency(value)} /></PieChart></ResponsiveContainer>}</div><div className="space-y-2">{pieData.map((item, index) => <div key={item.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: colors[index % colors.length] }} />{item.name}</span><strong>{formatCurrency(item.value)}</strong></div>)}</div></div></section>
    <section className="mb-5 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] p-5 shadow-[var(--shadow-soft)]"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Profit Contribution</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Products ranked by profit</h2></div><div className="h-72">{loading ? <Loader /> : <ResponsiveContainer width="100%" height="100%"><BarChart data={topProducts}><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `${Math.round(value / 1000)}k`} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltip} formatter={(value) => formatCurrency(value)} /><Bar dataKey="profit" name="Profit" fill="#059669" radius={[8, 8, 0, 0]} /><Bar dataKey="revenue" name="Revenue" fill="#bae6fd" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-[var(--border-color)] bg-[var(--bg-panel)] shadow-[var(--shadow-soft)]"><div className="flex flex-col gap-2 border-b border-[var(--border-color)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-amber-600">Product Action Board</p><h2 className="mt-1 text-lg font-black text-[color:var(--text-strong)]">Stock coverage and product profitability</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{productRows.length} products</span></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-[var(--bg-soft)] text-left text-xs uppercase tracking-wide text-[color:var(--text-muted)]"><tr><th className="px-5 py-3">Product</th><th className="px-3 py-3 text-right">Stock</th><th className="px-3 py-3 text-right">Units Sold</th><th className="px-3 py-3 text-right">Revenue</th><th className="px-3 py-3 text-right">Profit</th><th className="px-3 py-3 text-right">Margin / Unit</th><th className="px-5 py-3 text-right">Stock Cover</th></tr></thead><tbody>{productRows.map((product) => <tr key={product._id || product.name} className="border-t border-[var(--border-color)]"><td className="px-5 py-3 font-bold">{product.name}</td><td className={`px-3 py-3 text-right font-semibold ${product.stock <= 5 ? "text-rose-700" : ""}`}>{product.stock}</td><td className="px-3 py-3 text-right">{product.quantity}</td><td className="px-3 py-3 text-right font-semibold">{formatCurrency(product.revenue)}</td><td className="px-3 py-3 text-right text-emerald-700">{formatCurrency(product.profit)}</td><td className="px-3 py-3 text-right">{formatCurrency(product.marginPerUnit)}</td><td className="px-5 py-3 text-right">{product.coverage === null ? "No sales" : `${product.coverage.toFixed(1)}x`}</td></tr>)}{!loading && !productRows.length ? <tr><td colSpan="7" className="px-5 py-10 text-center text-sm text-[color:var(--text-muted)]">No product data is available.</td></tr> : null}</tbody></table></div></section>
  </div>
}

function Loader() { return <div className="flex h-full items-center justify-center text-sm font-medium text-[color:var(--text-muted)]">Loading lubricant analytics...</div> }
